import { keccak256 } from 'ethers'

/**
 * The 0G Storage file Merkle root, recomputed from raw bytes.
 *
 * ## Why this exists
 *
 * A model delivered by 0G Compute is content-addressed on 0G Storage by this
 * root hash, and the same hash is committed on-chain in the deliverable. To
 * retrieve a model over plain HTTP (the Windows-safe path — see `retrieval.ts`)
 * and still be sure we got the right bytes, we have to recompute the root from
 * what we downloaded and compare it to what the chain says. The chain is
 * authoritative; the indexer gateway is not.
 *
 * ## The algorithm, mirrored from `@0gfoundation/0g-storage-ts-sdk`
 *
 * This is a faithful, dependency-free re-implementation of the SDK's
 * `AbstractFile.merkleTree()` (v1.2.11), which is the function that produced the
 * root during upload. Getting it byte-identical is the whole point, so it is
 * pinned by a known-answer test (`storage-hash.test.ts`) whose vectors were
 * generated by running the real SDK — see that file's header.
 *
 * The shape of it:
 *   1. The file is right-padded with zero chunks to a "flow" size: the chunk
 *      count is rounded up by `computePaddedSize`, then multiplied by 256.
 *   2. The padded bytes are cut into 256 KiB segments (1024 × 256-byte chunks).
 *   3. Each segment's root is a binary Merkle tree over its 256-byte chunks,
 *      leaves hashed with `keccak256(chunk)`.
 *   4. The file root is a binary Merkle tree over the per-segment roots.
 *
 * The tree-building order is not a textbook one: the SDK pairs from the front of
 * a queue and rotates an odd trailing node to the back. `buildRoot` reproduces
 * that exactly, because a "cleaner" pairing would give a different hash.
 */

/** 0G Storage constants — do not retune; they define the hash. */
const CHUNK_SIZE = 256
const SEGMENT_MAX_CHUNKS = 1024
const SEGMENT_SIZE = CHUNK_SIZE * SEGMENT_MAX_CHUNKS

/** `numSplits(total, unit)` — chunks needed to hold `total` bytes. */
function numSplits(total: number, unit: number): number {
  if (total <= 0) return 0
  return Math.floor((total - 1) / unit) + 1
}

/** Smallest power of two ≥ input, matching the SDK's `nextPow2` (input ≥ 1). */
function nextPow2(input: number): number {
  if (input <= 1) return 1
  if (input > 0x7fffffff) return Math.pow(2, Math.ceil(Math.log2(input)))
  let x = input - 1
  x |= x >> 16
  x |= x >> 8
  x |= x >> 4
  x |= x >> 2
  x |= x >> 1
  return x + 1
}

/** Flow padding: how many chunks the file is padded up to before segmenting. */
function paddedChunkCount(chunks: number): number {
  const chunksNextPow2 = nextPow2(chunks)
  if (chunksNextPow2 === chunks) return chunksNextPow2
  const minChunk = chunksNextPow2 >= 16 ? Math.floor(chunksNextPow2 / 16) : 1
  return numSplits(chunks, minChunk) * minChunk
}

/** Total padded size in bytes for a file of `size` bytes (flow padding on). */
function paddedSizeBytes(size: number): number {
  return paddedChunkCount(numSplits(size, CHUNK_SIZE)) * CHUNK_SIZE
}

/** keccak256 over the concatenation of two 0x-prefixed 32-byte hashes. */
function combine(left: string, right: string): string {
  return keccak256(`0x${left.slice(2)}${right.slice(2)}`)
}

/**
 * Build a Merkle root from ordered leaf hashes, reproducing the SDK's queue
 * rotation exactly. Returns the sole leaf when there is only one.
 */
function buildRoot(leaves: string[]): string {
  const n = leaves.length
  if (n === 0) throw new Error('cannot build a Merkle root from zero leaves')

  const queue: string[] = []
  for (let i = 0; i < n; i += 2) {
    if (i === n - 1) {
      queue.push(leaves[i]!)
      continue
    }
    queue.push(combine(leaves[i]!, leaves[i + 1]!))
  }

  while (queue.length > 1) {
    const numNodes = queue.length
    for (let i = 0; i < Math.floor(numNodes / 2); i++) {
      const left = queue.shift()!
      const right = queue.shift()!
      queue.push(combine(left, right))
    }
    if (numNodes % 2 === 1) {
      queue.push(queue.shift()!)
    }
  }

  return queue[0]!
}

/** The Merkle root of a single (already 256-aligned) segment's chunks. */
function segmentRoot(segment: Uint8Array): string {
  const leaves: string[] = []
  for (let offset = 0; offset < segment.length; offset += CHUNK_SIZE) {
    leaves.push(keccak256(segment.subarray(offset, offset + CHUNK_SIZE)))
  }
  return buildRoot(leaves)
}

/**
 * Compute the 0G Storage file Merkle root of `bytes`, as a 0x-prefixed hex
 * string. Byte-for-byte compatible with what the 0G Storage SDK committed at
 * upload time.
 */
export function zgStorageRoot(bytes: Uint8Array): string {
  if (bytes.length === 0) throw new Error('cannot hash an empty artifact')

  const padded = paddedSizeBytes(bytes.length)
  const segmentRoots: string[] = []

  for (let offset = 0; offset < padded; offset += SEGMENT_SIZE) {
    const segLen = Math.min(SEGMENT_SIZE, padded - offset)
    const segment = new Uint8Array(segLen) // zero-filled: this is the padding
    if (offset < bytes.length) {
      const copyEnd = Math.min(offset + segLen, bytes.length)
      segment.set(bytes.subarray(offset, copyEnd), 0)
    }
    segmentRoots.push(segmentRoot(segment))
  }

  return buildRoot(segmentRoots)
}
